=== MaxLebed/scholarpubsearch/XMLMessages/schemas/request.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/request/" targetNamespace="http://www.example.org/request/">

    <complexType name="Publication">
    	<sequence>
    		<element name="title" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="author" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="year" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="journal" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="summary" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="pdfLink" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="bibtex" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="subjectArea" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="pagesCount" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
            <element name="keyword" type="string" maxOccurs="unbounded" minOccurs="0"></element>
        </sequence>
    </complexType>


    

    
    






    <simpleType name="AllowedAtribute">
    	<restriction base="string">
    		<enumeration value="JOURNAL"></enumeration>
    		<enumeration value="SUMMARY"></enumeration>
    		<enumeration value="PDF"></enumeration>
    		<enumeration value="BIBTEX"></enumeration>
    		<enumeration value="SUBJECT"></enumeration>
    		<enumeration value="PAGES"></enumeration>
    		<enumeration value="KEYWORDS"></enumeration>
    	</restriction>
    </simpleType>



    <element name="specifyingPublication">
    	<complexType>
    		<sequence>
    			<element name="atribute" type="tns:AllowedAtribute"></element>
    			<element name="publications" type="tns:Publication" maxOccurs="unbounded" minOccurs="1"></element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== MaxLebed/scholarpubsearch/trunk/XMLMessages/examples/REQUESTexample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 (http://www.altova.com)-->
<tns:specifyingPublication xsi:schemaLocation="http://www.example.org/request/ request.xsd" xmlns:tns="http://www.example.org/request/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<atribute>BIBTEX</atribute>
	<publications>
		<title>String</title>
		<author>String</author>
		<author>String</author>
		<author>String</author>
		<year>0</year>
		<journal>String</journal>
		<summary>String</summary>
		<pdfLink>String</pdfLink>
		<bibtex>String</bibtex>
		<subjectArea>String</subjectArea>
		<pagesCount>String</pagesCount>
		<keyword>String</keyword>
		<keyword>String</keyword>
		<keyword>String</keyword>
	</publications>
	<publications>
		<title>String</title>
		<author>String</author>
		<author>String</author>
		<author>String</author>
		<year>0</year>
		<journal>String</journal>
		<summary>String</summary>
		<pdfLink>String</pdfLink>
		<bibtex>String</bibtex>
		<subjectArea>String</subjectArea>
		<pagesCount>String</pagesCount>
		<keyword>String</keyword>
		<keyword>String</keyword>
		<keyword>String</keyword>
	</publications>
	<publications>
		<title>String</title>
		<author>String</author>
		<author>String</author>
		<author>String</author>
		<year>0</year>
		<journal>String</journal>
		<summary>String</summary>
		<pdfLink>String</pdfLink>
		<bibtex>String</bibtex>
		<subjectArea>String</subjectArea>
		<pagesCount>String</pagesCount>
		<keyword>String</keyword>
		<keyword>String</keyword>
		<keyword>String</keyword>
	</publications>
</tns:specifyingPublication>
